### PR TITLE
[kevin integration] driver enhancements

### PR DESCRIPTION
**Pull request by fmessmer**

### CODE REVIEW

**Comment by fmessmer** [comment]
eventually, the driver did not initialize because it was not re-calibrated....we should find a condition for "not calibrated" and report that as a different failure message during the init_cb

**Comment by fmessmer** [comment]
the problem with init was the robot arm not being calibrated
this is also expressed in the ErrorCode -3015
we should add (at least an informal) KeyValue pair to the diagnostics which logs the present ErrorCodes
we could collect these in a dict where the key is the ErrorCode and the value is the number if occurences for example
the dict should get reset to empty whenever the arm is operational

**Comment by benmaidel** [comment]
3015 = calibration not ready
3128 = encoder battery down

**Comment by fmessmer** [comment]
follow-up issue for the error codes in diagnostics is https://github.com/mojin-robotics/kevin/issues/240

**Pull request merged**
