### PR TITLE
Feature/doosan hack

### PR DESCRIPTION
**Pull request by floweisshardt**
fixes https://github.com/mojin-robotics/kevin/issues/27

### CODE REVIEW

**Comment by floweisshardt** [comment]
approved by @Deleh in https://github.com/mojin-robotics/kevin/issues/27

**Comment by benmaidel** [comment]
I've rebased the branch

**Comment by fmessmer** [comment]
this should really be solved properly in https://github.com/mojin-robotics/kevin/issues/41

**Comment by fmessmer** [comment]
I'll merge this even though everything in me argues against doing that, i.e. merging something called "hack"

**Pull request merged**
